### test
GET http://localhost:8080/users/2

### save
POST http://localhost:8080/users
Content-Type: application/json

{
  "password": "password",
  "name": "name",
  "phone": "phone"
}

### error
GET http://localhost:8080/broads/error

